services:
  weather_test_bot:
    build: .
    image: weather_test_bot
    container_name: weather_test_bot
    env_file: "app.env"
    volumes:
      - ./:/bot
    command: ["python3", "main.py"]
    restart: no